### ISSUE TITLE
How to apply pop out effect on md-card (angualr materical sheet)

### ISSUE THREAD

**Issue by osi-bhushankumar** [dfsq/ngView-animation-effects#11]
Hi,

I am looking for same pop-out effect on angular material sheet. I want to use 'pop-out' effect to hide some content and show next content.

That is exactly you are doing on ng-view. But in my case while click on 'Next' the another md-card (material sheet) will be change,

Does it possible using this library ?

**Comment by dfsq** [comment]
Hello,

Yes, it should be possible, but ngView-animation effects is not a library, it's just a demonstration of Angular ngAnimate capabilities for working with ngRoute. So you should be able to apply the same principals to other stuff too.

**Comment by osi-bhushankumar** [comment]
okay,

I am working on that. If you found some needful reference , please let me know.
