### ISSUE TITLE
Animation moves positioning of partials

### ISSUE THREAD

**Issue by GDriver88** [dfsq/ngView-animation-effects#4]
HI I have 2 partials and one Ng view.

Partial 1-header

Ng-view-class slide animation

Partial 2..footer

When I use the slide animation...it makes the partial view...the header move up and stay there.

How do I stop this from happening?

thanks,

**Comment by dfsq** [comment]
I guess there is something with your styles or setup. I can't see why ngView can affect partial view. If you could setup a demo with the issue, I would say more. Without seeing it it's hard to tell.

**Comment by GDriver88** [comment]
Hi thank you for your quick response.

I'm actually at home but when I get to work tomorrow...I shall link you to it.

Thanks, Garry

**Comment by GDriver88** [comment]
Hi thank you for your email..
Currently my website looks like example 4.
When I use the slide effect.  It slides across...then the footer appears upwards and stays there. As seen in example 5:
I currently have this in index.html


 <div id="header" ng-include="'partials/header.html'"></div>
   <div ng-view class="slide"></div>


  <div id="oilFooter" ng-include="'partials/footer.html'"></div>
ThanksGarry


Date: Tue, 24 Feb 2015 10:57:30 -0800

**Comment by dfsq** [comment]
Closing, probably has been resolved long time ago.
