### ISSUE TITLE
Reverse slide direction

### ISSUE THREAD

**Issue by iamdtang** [dfsq/ngView-animation-effects#6]
Very useful repo, thanks! Do you know how to reverse the slide transition in the other direction, like for a back button?

**Comment by dfsq** [comment]
It's implemented in this project. Check [backAnimation.js](https://github.com/dfsq/ngView-animation-effects/blob/master/app/js/directives/backAnimation.js) directive. A little clumsy but does the job.

**Comment by dannygoncalves** [comment]
How do you work with that directive right from a back button?

**Comment by dfsq** [comment]
Did you check backAnimation.js directive?
