### ISSUE TITLE
Prev navigation

### ISSUE THREAD

**Issue by dannygoncalves** [dfsq/ngView-animation-effects#8]
Hi, i forked your repo and more than issue is a request or guidance

First thanks for this mini-project.

Second, i need to use it to navigate back and forth between views, i managed to modify the pagesController in order to move with a **prev** and **next** buttons and left only the slide effect, however i cannot make it slide the other way like you do when pressing the back button on browser, how can i do it?

Thanks in advance!

**Edit**
I solved it by adding a new class in css that switches left from negative to positive and also for leave.
Then when the corresponding event is clicked i add or remove the class.

**Comment by dfsq** [comment]
Did you check backAnimation directive? This is what handles back navigation 
https://github.com/dfsq/ngView-animation-effects/blob/master/app/js/directives/backAnimation.js
